### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by bcamac** [appnexus/schema-tool#36]
Following the wiki (https://corpwiki.appnexus.com/display/engineering/How+To+Use+The+%27schema%27+Script) and got to the point of 'schema rebuild' which fails with:
```
Bringing all the way down
Downgraded

Bringing all the way back up
Running alter: 137823105930-init-up.sql
An exception has occurred... Sorry. You should file a ticket in
our issue tracker: http://github.com/appnexus/schema-tool/issues

Error: 2, No such file or directory
```
Anyway to get more details about which file/directory its looking for?
BTW, the file 137823105930-init-up.sql does exist in the directory.

**Comment by JohnMurray** [comment]
@bcamac You could try running the command with the `-v` option. 

Additionally, it doesn't seem like it's running any of the `down` alters. Have any been applied yet? If not, you could try running with `schema up and see how that works. The tool uses the actual mysql and postgres binaries to perform it's operations (aside from reading the current DB state) so it might be that it cannot find the correct binary. Could you run the following commands for me (and share the results):

+ `which mysql`
+ `which psql`

Also, could you share the contents of your `config.json`?

**Comment by bcamac** [comment]
Your instincts were correct. Turned out neither mysql nor psql were in the shell's path (its a new machine setup).  After adding it to the path schema tool proceeds past that point.  
schema rebuild --force then worked (a few errors but its ok).  
Problem solved.  Thanks for your assistance.

**Comment by JohnMurray** [comment]
@bcamac glad all is working now. I'll add a ticket to provide more helpful error messages for this particular error.
