### ISSUE TITLE
Ordering of alters in PostgreSQL

### ISSUE THREAD

**Issue by nguyening** [appnexus/schema-tool#80]
When running `schema up`, a chain of alters is constructed from the alter files.
`schema-tool` then grabs the history of alters that have been run for a PostgreSQL DB via a simple `SELECT *`: [schematool/db/_pg.py](https://github.com/appnexus/schema-tool/blob/349563ffda61deacf0ebc5ddbbc94a0e35713fcc/schematool/db/_pg.py#L100-L102)

The history is then compared with the chain of alters, and it seems that the ordering is significant:
 [schematool/command/up.py](https://github.com/appnexus/schema-tool/blob/349563ffda61deacf0ebc5ddbbc94a0e35713fcc/schematool/command/up.py#L66-L79)

From the PostgreSQL docs:
> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on.

It seems that this should be patched to include an ordering, probably by the primary key and the timestamp.

**Comment by JohnMurray** [comment]
Agreed. It should definitely include an ordering. At the moment it's likely safe to just order by the ID.
